/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej15Listeners;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author DAM2Alu5
 */
public class JFrameListeners extends javax.swing.JFrame {
Color original;
    ActionListener a=new ActionListener(){   
        
public void actionPerformed(ActionEvent ae){                 
System.out.println("No copies");
}

    };
    /**
     * Creates new form JFrameListeners
     */
    public JFrameListeners() {
        initComponents();
        
        original=jTextFieldOriginal.getBackground();
        KeyStroke ctrl_C = KeyStroke.getKeyStroke(KeyEvent.VK_C,java.awt.Event.CTRL_MASK, true);
        getRootPane().registerKeyboardAction(a,ctrl_C ,JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldOriginal = new javax.swing.JTextField();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelCopiaMensaje = new javax.swing.JLabel();
        jTextFieldCopia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaArrastrar = new javax.swing.JTextArea();
        jButtonArrastrar = new javax.swing.JButton();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelOculto = new javax.swing.JPanel();
        jLabelOculta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextFieldOriginal.setDragEnabled(true);
        jTextFieldOriginal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldOriginalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldOriginalFocusLost(evt);
            }
        });
        jTextFieldOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOriginalActionPerformed(evt);
            }
        });
        jTextFieldOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldOriginalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldOriginalKeyReleased(evt);
            }
        });

        jLabelMensaje.setText("Mensaje");

        jLabelCopiaMensaje.setText("Copia del mensaje:");

        jTextFieldCopia.setEditable(false);
        jTextFieldCopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCopiaActionPerformed(evt);
            }
        });

        jTextAreaArrastrar.setColumns(20);
        jTextAreaArrastrar.setRows(5);
        jScrollPane1.setViewportView(jTextAreaArrastrar);

        jButtonArrastrar.setText("Arrastrar");
        jButtonArrastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButtonArrastrarMouseDragged(evt);
            }
        });

        jPanelContenedor.setBackground(new java.awt.Color(204, 0, 51));
        jPanelContenedor.setForeground(new java.awt.Color(0, 255, 204));
        jPanelContenedor.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanelContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelContenedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelContenedorMouseExited(evt);
            }
        });

        jPanelOculto.setBackground(new java.awt.Color(0, 0, 204));
        jPanelOculto.setForeground(new java.awt.Color(0, 0, 255));

        jLabelOculta.setText("Oculto");

        javax.swing.GroupLayout jPanelOcultoLayout = new javax.swing.GroupLayout(jPanelOculto);
        jPanelOculto.setLayout(jPanelOcultoLayout);
        jPanelOcultoLayout.setHorizontalGroup(
            jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelOcultoLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabelOculta)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        jPanelOcultoLayout.setVerticalGroup(
            jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelOcultoLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabelOculta)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jPanelOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCopiaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jButtonArrastrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCopia, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldOriginal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCopiaMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCopia, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonArrastrar)
                .addGap(20, 20, 20)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOriginalActionPerformed
        System.out.println("noseque");
    }//GEN-LAST:event_jTextFieldOriginalActionPerformed

    private void jTextFieldCopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCopiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCopiaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

           jPanelOculto.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOriginalKeyReleased

        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            System.out.println("Capturada la tecla enter");
    }//GEN-LAST:event_jTextFieldOriginalKeyReleased

    private void jTextFieldOriginalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOriginalFocusGained

        System.out.println("Se ha ganado el foco");
    }//GEN-LAST:event_jTextFieldOriginalFocusGained

    private void jTextFieldOriginalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOriginalFocusLost

        System.out.println("Se ha perdido el foco");
        jTextFieldCopia.setText(jTextFieldOriginal.getText());
        jTextAreaArrastrar.requestFocus();
    }//GEN-LAST:event_jTextFieldOriginalFocusLost

    
  


    
    
    private void jTextFieldOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOriginalKeyPressed
//jTextFieldCopia.setText(jTextFieldOriginal.getText());
        System.out.println("Tamaño actual: "+jTextFieldOriginal.getText().length() );
        int aux = jTextFieldOriginal.getText().length();
        if (aux>=30){
            jTextFieldOriginal.setForeground(Color.red);
            jTextFieldOriginal.setBackground(Color.yellow);
        }else if(aux>=25){
            jTextFieldOriginal.setForeground(Color.yellow);
            jTextFieldOriginal.setBackground(Color.BLUE);
        }else if (aux<25){
            jTextFieldOriginal.setForeground(Color.black);
            jTextFieldOriginal.setBackground(Color.white);
        }
        
    }//GEN-LAST:event_jTextFieldOriginalKeyPressed

    private void jButtonArrastrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonArrastrarMouseDragged

        System.out.println("Arrastrando a la posicion "+evt.getPoint());
    }//GEN-LAST:event_jButtonArrastrarMouseDragged

    private void jPanelContenedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContenedorMouseEntered

        jPanelOculto.setVisible(true);
    }//GEN-LAST:event_jPanelContenedorMouseEntered

    private void jPanelContenedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContenedorMouseExited
    
        jPanelOculto.setVisible(false);
    }//GEN-LAST:event_jPanelContenedorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListeners().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArrastrar;
    private javax.swing.JLabel jLabelCopiaMensaje;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelOculta;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelOculto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaArrastrar;
    private javax.swing.JTextField jTextFieldCopia;
    private javax.swing.JTextField jTextFieldOriginal;
    // End of variables declaration//GEN-END:variables
}
